### PR TITLE
Upload build upon action completion.

### PR DESCRIPTION
**Pull request by LeWolfYT**

### CODE REVIEW

**Review by sidgames5 — CHANGES_REQUESTED** [review]
Please make the workflow output a file named "chatlink-latest+bukkit_[bukkit api version]"

And please make the download link for stable releases go to the modrinth page https://modrinth.com/plugin/chatlink/versions

**Comment by sidgames5** [comment]
If you are not sure what the bukkit api version is, you can find it in src/main/resources/plugin.yml. It is just the minimum minecraft version

**Comment by LeWolfYT** [comment]
it’s gonna have to be embedded in the file

**Comment by LeWolfYT** [comment]
ok its done

**Review by sidgames5 — APPROVED** [review]
Since you are unable to get the bukkit api version, i will just merge it and set it to 'chatlink-latest+bukkit'

**Pull request merged**
