### PR TITLE
Don't run a build when non-functional files are updated, plus future-proofing for MessageEvents

### PR DESCRIPTION
**Pull request by LeWolfYT**
Non-functional files include:
- README.md
- CHANGELOG.md
- .gitignore
Guild events will be deprecated in JDA v5.0

### CODE REVIEW

**Review by sidgames5 — CHANGES_REQUESTED** [review]
You have removed the channel ID verification from MessageEvents.java. This is necessary.

**Comment by LeWolfYT** [comment]
Except I didn't?????

**Comment by sidgames5** [comment]
Sorry my browser had an issue and didnt show that for some reason.

**Comment by LeWolfYT** [comment]
bbuh

**Review by sidgames5 — APPROVED** [review]

**Pull request merged**
